---

- name: Create VPC in {{region}}
  amazon.aws.ec2_vpc_net: 
   region: "{{region }}"
   name: "{{ vpc_name }}"
   cidr_block: "{{ cidr_block }}"
   tenant: dedicated
  register: vpc 

- name: Create Subnet
  amazon.aws.ec2_vpc_subnet:
   region: "{{ region }}"
   vpc_id: "{{ vpc.vpc_id }}"
   cisr: "{{ subnet-A }}"
   az: "{{ zone }}"
  register: subnet

- name: create internet gateway
  amazon.aws.ec2_vpc_igw:
   region: "{{ region }}"
   vpc_id: "{{ vpc.vpc_id }}"
  register: igw

- name: Set up public subnet route table
  amazon.aws.ec2_vpc_route_table:
   region: "{{region}}"
   vpc_id: "{{ vpc.vpc_id }}"
   subnets:
    - "{{ subnet.subnet_id  }}"
   routes:
    - dest: 0.0.0.0/0
      gateway_id: "{{ igw.gateway_id }}"
