---
- name: Create VPC
  amazon.aws.ec2_vpc_net_info:
<<<<<<< HEAD
=======
   region: "{{ region }}"
>>>>>>> d8d1fea4ff3de435096b2a6d6a4c66ef2c55deae
   register: vpc_info

- name: List vpc_list
  debug:
    msg: "{{ vpc_info }}"


